# Generated by Django 3.1.2 on 2020-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_news_news_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
