# Generated by Django 3.1.2 on 2020-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201028_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.URLField(default='static/img/bg.jpg', null=True),
        ),
    ]
