# Generated by Django 3.1.2 on 2021-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('body', models.TextField()),
                ('img', models.CharField(default='static/img/bg.jpg', max_length=300, null=True)),
                ('keywords', models.CharField(default='NA', max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('source', models.CharField(default='kokoroyin', max_length=300)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
